In [1]:
pip install pandas

Requirement already satisfied: pandas in /Users/macpc/Documents/projects/python-classics/.venv/lib/python3.14/site-packages (3.0.2)
Requirement already satisfied: numpy>=2.3.3 in /Users/macpc/Documents/projects/python-classics/.venv/lib/python3.14/site-packages (from pandas) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/macpc/Documents/projects/python-classics/.venv/lib/python3.14/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Users/macpc/Documents/projects/python-classics/.venv/lib/python3.14/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd

In [3]:
df=pd.read_csv("./student.csv")

In [9]:
df.tail()

  Unnamed: 0    Name  height  weight  sex       bdate       city major
2   f1357689    John   180.4    80.3    1   1980/5/30     Tainan  Stat
3   e1374659   Keven   182.5    77.6    1  1980/11/19     Taipei    EE
4   s7758347    JoJo   170.3    50.3    2   1980/1/27     Taipei  CSIE
5   s1334987   Emily   168.5    53.6    2  1982/10/13  Kaohsiung  CSIE
6   e1384726  Ubuntu   177.0    68.3    1    1981/7/6  Kaohsiung    EE

In [7]:
df.describe()

           height     weight       sex
count    7.000000   7.000000  7.000000
mean   173.814286  65.078571  1.428571
std      6.927103  12.106811  0.534522
min    163.000000  50.300000  1.000000
25%    169.400000  54.300000  1.000000
50%    175.000000  68.300000  1.000000
75%    178.700000  74.025000  2.000000
max    182.500000  80.300000  2.000000

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  7 non-null      str
 1   Name        7 non-null      str
 2   height      7 non-null      float64
 3   weight      7 non-null      float64
 4   sex         7 non-null      int64
 5   bdate       7 non-null      str
 6   city        7 non-null      str
 7   major       7 non-null      str
dtypes: float64(2), int64(1), str(5)
memory usage: 804.0 bytes