Car dealer and market activity

In [2]:
print("hi")

hi

In [3]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt

In [4]:
df=pd.read_csv("data/ca-dealers-used.csv")
df.head()

/var/folders/49/qytw62_j093by3rd914msvn40000gn/T/ipykernel_8019/1893495782.py:1: DtypeWarning: Columns (0: fuel_type, 1: engine_block) have mixed types. Specify dtype option on import or set low_memory=False.
  df=pd.read_csv("data/ca-dealers-used.csv")

,id,vin,price,miles,stock_no,year,make,model,trim,body_type,...,drivetrain,transmission,fuel_type,engine_size,engine_block,seller_name,street,city,state,zip
0,b39ea795-eca9,19UNC1B01HY800062,179999.0,9966.0,V-P4139,2017.0,Acura,NSX,Base,Coupe,...,4WD,Automatic,Electric / Premium Unleaded,3.5,V,edmundston honda,475 Rue Victoria,Edmundston,NB,E3V 2K7
1,026cb5b1-6e3e,19UNC1B02HY800023,179995.0,5988.0,PPAP70374,2017.0,Acura,NSX,Base,Coupe,...,4WD,Automatic,Electric / Premium Unleaded,3.5,V,garage daniel lessard,2795 Route-du-prsident-kennedy,Notre-dame-des-pins,QC,G0M 1K0
2,5cd5d5b2-5cc2,19UNC1B02HY800071,168528.0,24242.0,B21085,2017.0,Acura,NSX,Base,Coupe,...,4WD,Automatic,Electric / Premium Unleaded,3.5,V,lougheed acura,1388 Lougheed Highway,Coquitlam,BC,V3K 6S4
3,b32473ed-5922,19UNC1B02LY800001,220000.0,6637.0,AP5333,2020.0,Acura,NSX,Base,Coupe,...,4WD,Automatic,Electric / Premium Unleaded,3.5,V,drive autogroup,1305 Parkway Suite 600,Pickering,ON,L1V 3P2
4,ac40c9fc-0676,19UNC1B02LY800001,220000.0,6637.0,AP5333,2020.0,Acura,NSX,Base,Coupe,...,4WD,Automatic,Electric / Premium Unleaded,3.5,V,acura pickering,575 Kingston Road,Pickering,ON,L1V 3N7

In [5]:
df.isna().sum()

id                  0
vin                 0
price           35117
miles           27013
stock_no        27693
year               17
make                0
model            4794
trim            38779
body_type       34025
vehicle_type    38238
drivetrain      38995
transmission    35681
fuel_type       70813
engine_size     72653
engine_block    73164
seller_name      2232
street           7929
city             7774
state            7836
zip              7769
dtype: int64

In [6]:
df.shape

(393603, 21)

In [7]:
cols_to_drop=['id', 'vin', 'trim', 'stock_no', 'street', 'zip', 'seller_name', 'city']
df=df.drop(cols_to_drop, axis=1)

df.shape

(393603, 13)

In [8]:
df.dtypes

price           float64
miles           float64
year            float64
make                str
model               str
body_type           str
vehicle_type        str
drivetrain          str
transmission        str
fuel_type           str
engine_size     float64
engine_block        str
state               str
dtype: object

In [9]:
df=df.dropna(axis=0)

In [10]:
df[['make','model','body_type','vehicle_type','drivetrain','transmission','fuel_type']]=df[['make','model','body_type','vehicle_type','drivetrain','transmission','fuel_type']].astype('string')

In [11]:
df.shape

(269552, 13)

In [12]:
df.isna().sum()

price           0
miles           0
year            0
make            0
model           0
body_type       0
vehicle_type    0
drivetrain      0
transmission    0
fuel_type       0
engine_size     0
engine_block    0
state           0
dtype: int64

In [13]:
df.head()

,price,miles,year,make,model,body_type,vehicle_type,drivetrain,transmission,fuel_type,engine_size,engine_block,state
0,179999.0,9966.0,2017.0,Acura,NSX,Coupe,Car,4WD,Automatic,Electric / Premium Unleaded,3.5,V,NB
1,179995.0,5988.0,2017.0,Acura,NSX,Coupe,Car,4WD,Automatic,Electric / Premium Unleaded,3.5,V,QC
2,168528.0,24242.0,2017.0,Acura,NSX,Coupe,Car,4WD,Automatic,Electric / Premium Unleaded,3.5,V,BC
3,220000.0,6637.0,2020.0,Acura,NSX,Coupe,Car,4WD,Automatic,Electric / Premium Unleaded,3.5,V,ON
4,220000.0,6637.0,2020.0,Acura,NSX,Coupe,Car,4WD,Automatic,Electric / Premium Unleaded,3.5,V,ON

In [14]:
df['make'].unique()

<ArrowStringArray>
[        'Acura',         'Dodge',      'Chrysler',           'RAM',
          'Ford',     'Chevrolet',         'Buick',      'Cadillac',
           'GMC',         'Lexus',    'Volkswagen',           'BMW',
 'Mercedes-Benz',        'Hummer',       'Lincoln',         'Volvo',
      'INFINITI',        'Toyota',    'Land Rover',          'Audi',
          'MINI',       'Porsche',      'Maserati',    'Am General',
          'Jeep',        'Nissan',         'Mazda',        'Jaguar',
         'Honda',       'Pontiac',    'Oldsmobile',        'Saturn',
      'Plymouth',       'Mercury',        'Suzuki',           'Kia',
       'Hyundai',         'Scion',    'Mitsubishi',        'Subaru',
          'FIAT',       'GENESIS',         'Lotus',          'Saab',
       'Ferrari',       'McLaren',   'Rolls-Royce',       'Bentley',
  'Aston Martin',       'Maybach',         'smart',    'Alfa Romeo',
   'Lamborghini',         'KARMA']
Length: 54, dtype: string

In [15]:
df['make']=df['make'].apply(lambda x : x.lower().replace(' ', '_').replace('-','_'))

df['make'].unique()

<ArrowStringArray>
[        'acura',         'dodge',      'chrysler',           'ram',
          'ford',     'chevrolet',         'buick',      'cadillac',
           'gmc',         'lexus',    'volkswagen',           'bmw',
 'mercedes_benz',        'hummer',       'lincoln',         'volvo',
      'infiniti',        'toyota',    'land_rover',          'audi',
          'mini',       'porsche',      'maserati',    'am_general',
          'jeep',        'nissan',         'mazda',        'jaguar',
         'honda',       'pontiac',    'oldsmobile',        'saturn',
      'plymouth',       'mercury',        'suzuki',           'kia',
       'hyundai',         'scion',    'mitsubishi',        'subaru',
          'fiat',       'genesis',         'lotus',          'saab',
       'ferrari',       'mclaren',   'rolls_royce',       'bentley',
  'aston_martin',       'maybach',         'smart',    'alfa_romeo',
   'lamborghini',         'karma']
Length: 54, dtype: str

In [16]:
df['body_type']=df['body_type'].apply(lambda x: x.lower().replace(' ', '_').replace('-','_'))

df['body_type'].unique()

<ArrowStringArray>
[           'coupe',            'sedan',           'pickup',
              'suv',      'convertible',        'hatchback',
            'targa',    'passenger_van',        'cargo_van',
      'chassis_cab',          'minivan',         'mini_mpv',
        'crossover',            'wagon',          'cutaway',
        'micro_car',            'combi',          'car_van',
         'roadster', 'commercial_wagon']
Length: 20, dtype: str

In [17]:
df['vehicle_type'].unique()

<ArrowStringArray>
['Car', 'Truck']
Length: 2, dtype: string

In [18]:
df['drivetrain'].unique()

<ArrowStringArray>
['4WD', 'FWD', 'RWD']
Length: 3, dtype: string

In [19]:
df['transmission'].unique()

<ArrowStringArray>
['Automatic', 'Manual']
Length: 2, dtype: string

In [20]:
df['fuel_type'].unique()

<ArrowStringArray>
[        'Electric / Premium Unleaded',                                 'E85',
            'E85 / Unleaded; Unleaded',                      'Unleaded / E85',
                 'Unleaded / Unleaded', 'E85 / Unleaded; Unleaded / Unleaded',
          'Premium Unleaded; Unleaded',         'Premium Unleaded / Unleaded',
        'Compressed Natural Gas / Lpg',   'Compressed Natural Gas / Unleaded',
                           'Biodiesel',              'E85 / Premium Unleaded',
                      'Electric / E85',              'Compressed Natural Gas',
    'Compressed Natural Gas; Unleaded',                 'Unleaded / Electric',
           'Diesel / Premium Unleaded',                              'Diesel',
                            'Electric',                            'Unleaded',
                      'E85 / Unleaded',                    'Premium Unleaded',
                 'Electric / Unleaded']
Length: 23, dtype: string

In [21]:
gasoline={
    'gas',
    'E85 / Unleaded',
    'Unleaded',
    'Unleaded; Unleaded / E85', 
    'Unleaded / E85',
    'E85 / Unleaded; Unleaded', 
    'Premimum Unleaded / Unleaded',
    'E85 / Premium Unleaded; E85 / Unleaded',
    'E85', 'E85 / Premium Unleaded',
    'Compressed Natural Gas / Lp',
    'Compressed Natural Gas / Unleaded',
    'Compressed Natural Gas',
    'E85 / Unleaded; Unleaded / Unleaded',
    'Diesel / Premium Unleaded', 
    'E85 / Unleaded; Unleaded / E85', 
    'Unleaded / Unleaded', 
    'Diesel; Unleaded',
    'Unleaded / Premium Unleaded',
    'Premium Unleaded / E85',
    'M85 / Unleaded',
    'E85',
    'Premium Unleaded / Unleaded',
    'Premium Unleaded',
    'Compressed Natural Gas; Unleaded',
    'Premium Unleaded; Unleaded',
}
biodiesel={
    'Biodiesel'
}
hybrid={
    'Electric / Unleaded',
    'Electric',
    'Electric / E85',
    'Electric / Premium Unleaded',
    'Electric / E85',
    'Electric / Hydrogen',
    'Electric / Premium Unleaded; Electric / Unleaded',
    'Electric / Premium Unleaded; Premium Unleaded',
    'Unleaded / Electric'
}

other={
    'Hydrogen',
    'Premium Unleaded / Natural Gas',
    'Compressed Natural Gas / Lpg',
    'Compressed Natural Gas', 'Propane',
    'Flex Fuel Vehicle'

}

def preprocess_fuel_type(x):
    if x in gasoline:
        return "gasoline"
    elif x in biodiesel:
        return "biodiesel"
    elif x in hybrid:
        return "hybrid"
    else:
        return "other"
    
df['fuel_type']=df['fuel_type'].apply(preprocess_fuel_type)

In [22]:
df['fuel_type'].unique()

<ArrowStringArray>
['hybrid', 'gasoline', 'other', 'biodiesel']
Length: 4, dtype: str

In [23]:
df['engine_size'].unique()

array([3.5, 2.7, 3.6, 5.7, 4. , 5. , 5.4, 3. , 1.4, 1.5, 4.6, 6. , 6.6,
       5.3, 6.2, 6.1, 2.4, 1.6, 2. , 3.3, 1.8, 2.5, 0.6, 2.9, 4.7, 6.5,
       5.9, 3.2, 6.7, 6.4, 7.3, 2.8, 1.9, 2.2, 2.1, 5.2, 8. , 3.7, 2.3,
       1. , 3.8, 3.9, 6.8, 4.2, 3.1, 3.4, 4.5, 4.8, 4.3, 8.1, 7.4, 1.7,
       5.6, 1.3, 1.2, 4.4, 6.3, 8.3, 8.4, 7. , 5.8, 5.5, 2.6, 0.9])

In [24]:
df['engine_block'].unique()

<ArrowStringArray>
['V', 'I', 'H']
Length: 3, dtype: str

In [25]:
df['state'].unique()

<ArrowStringArray>
['NB', 'QC', 'BC', 'ON', 'AB', 'MB', 'SK', 'NS', 'PE', 'NL', 'YT', 'NC', 'OH',
 'SC']
Length: 14, dtype: str

In [26]:
unique_make_model= df.groupby(['make', 'model']).size().reset_index(name='count')

non_unique_rows = unique_make_model[unique_make_model['count']>1]

df_filtered= df.merge(non_unique_rows, on=['make', 'model'], how='inner').drop(['count'],axis=1)

In [27]:
df_filtered.shape

(269493, 13)

In [65]:
df_filtered.to_csv('data/done/used_car_canada_clean.csv', index=False, header=True)

# Modeling

In [34]:
df=pd.read_csv('data/used_car_canada_clean.csv')
df.head()

,price,miles,year,make,model,body_type,vehicle_type,drivetrain,transmission,fuel_type,engine_size,engine_block,state
0,179999.0,9966.0,2017.0,Acura,NSX,coupe,Car,4WD,Automatic,hyrid,3.5,V,NB
1,179995.0,5988.0,2017.0,Acura,NSX,coupe,Car,4WD,Automatic,hyrid,3.5,V,QC
2,168528.0,24242.0,2017.0,Acura,NSX,coupe,Car,4WD,Automatic,hyrid,3.5,V,BC
3,220000.0,6637.0,2020.0,Acura,NSX,coupe,Car,4WD,Automatic,hyrid,3.5,V,ON
4,220000.0,6637.0,2020.0,Acura,NSX,coupe,Car,4WD,Automatic,hyrid,3.5,V,ON

In [49]:
df["make"]

0                 Acura
1                 Acura
2                 Acura
3                 Acura
4                 Acura
              ...
269488    Mercedes-Benz
269489    Mercedes-Benz
269490    Mercedes-Benz
269491    Mercedes-Benz
269492          Porsche
Name: make, Length: 269493, dtype: str

In [51]:
cat_cols = [c for c in df.columns if df[c].dtypes == 'string' and c != "price"]
num_cols = [c for c in df.columns if df[c].dtypes != 'string' and c != "price"]

print("Categorical:",cat_cols)
print("Numerical", num_cols)

Categorical: ['make', 'model', 'body_type', 'vehicle_type', 'drivetrain', 'transmission', 'fuel_type', 'engine_block', 'state']
Numerical ['miles', 'year', 'engine_size']

In [54]:
from sklearn.model_selection import train_test_split

X = df.drop(['price'], axis=1)
y = df['price']

X_train, X_test, y_train, y_test = train_test_split(X, y, stratify=df[['make', 'model']], test_size=0.2, shuffle=True, random_state=42)

In [55]:
X_train['body_type'].value_counts()

body_type
suv                 100843
sedan                54038
pickup               22226
hatchback            20438
minivan               7428
coupe                 4696
wagon                 1703
convertible           1481
cargo_van             1197
mini_mpv               487
passenger_van          206
cutaway                181
targa                  177
micro_car              150
car_van                103
chassis_cab            101
crossover               90
combi                   40
roadster                 8
commercial_wagon         1
Name: count, dtype: int64

In [56]:
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.compose import TransformedTargetRegressor
from sklearn.ensemble import HistGradientBoostingRegressor
import numpy as np


num_tf = Pipeline([
    ("imputer", SimpleImputer(strategy="median"))
])

cat_tf = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("onehot", OneHotEncoder(handle_unknown="ignore", sparse_output=False))
])

pre= ColumnTransformer([
    ("num", num_tf, num_cols),
    ("cats", cat_tf, cat_cols)
])

regr = HistGradientBoostingRegressor(random_state=42)

model = TransformedTargetRegressor(
    regressor=Pipeline([("pre", pre), ("regr", regr)]),
    func=np.log1p, inverse_func=np.expm1
)

In [58]:
from sklearn.ensemble import GradientBoostingRegressor

model = Pipeline(
    steps=[
        ("preprocessor", preprocessor),
        ("regressor", GradientBoostingRegressor(random_state=42))
    ]
)

NameError: name 'preprocessor' is not defined

In [59]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, root_mean_squared_error, r2_score

X = df.drop(columns=["price"])
y = df["price"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model.fit(X_train, y_train)
y_pred=model.predict(X_test)

mae = mean_absolute_error(y_test, y_pred)
rmse = root_mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f"R^2={r2:.3f}, RMSE={rmse:.1f}, MAE={mae:.1f}")

R^2=0.866, RMSE=7541.3, MAE=2967.3

In [61]:
from sklearn.model_selection import KFold, cross_val_score
import numpy as np

kf = KFold(n_splits=5, shuffle=True, random_state=42)
cv_mae = -cross_val_score(model, X, y, cv=kf, scoring="neg_mean_absolute_error")
cv_rmse=np.sqrt(-cross_val_score(model, X, y, cv=kf, scoring="neg_mean_squared_error"))
cv_r2=cross_val_score(model, X, y, cv=kf, scoring="r2")

print(f"MAE: {cv_mae.mean():.1f} +/- {cv_mae.std():.1f}")
print(f"RMSE: {cv_rmse.mean():.1f} +/- {cv_rmse.std():.1f}")
print(f"R2: {cv_r2.mean():.3f} +/- {cv_r2.std():.3f}")

MAE: 2942.3 +/- 24.7
RMSE: 6679.0 +/- 544.5
R2: 0.885 +/- 0.014

In [63]:
from joblib import dump 
dump(model, 'model/model.joblib')

['model/model.joblib']

In [64]:
import sklearn
print(sklearn.__version__)

1.8.0